### ISSUE TITLE
Readonly properties as Enum

### ISSUE THREAD

**Issue by fayzzzm** [origamih/redux-action-type-factory#1]
Hey, @origamih. Hope you are doing well.
Everything is good, but enums have readonly properties. You could change your code to something like this: `readonly [K in T[number]]`. If you want, I can send a PR with some folder structure change and review it. 
Best regards

**Comment by huy-thp** [comment]
Oh yes, I didn’t think about this before. Please submit a PR, I will merge

**Comment by huy-thp** [comment]
https://github.com/origamih/redux-action-type-factory/pull/2
